#!/bin/bash
#PBS -N str_k&
#PBS -q q72h32c
#PBS -j oe
#PBS -m abe
#PBS -M test@gmail.com
#PBS -o str_k&.$PBS_JOBID
#PBS -l nodes=1:ppn=32
#PBS -l walltime=03:00:00:00
#PBS -V

cd $PBS_O_WORKDIR

module load parallel

infile=ONEA_sub.str
mparams=mainparams
eparams=extraparams
outdir=ONEA

mkdir ./$outdir;
cd ./$outdir;

parallel "structure -K & -D {}8582& -m ../$mparams -e ../$eparams -i ../$infile -o k&_{}.out" :::: <(seq 1 32);

